# Generated by Django 6.0.3 on 2026-04-06 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_created_by'),
        ('orders', '0002_order_paid_at_order_payment_method_and_more'),
    ]

    operations = [
    ]
